import { Music, Globe, Users } from 'lucide-react';

export const PLANS = [
  {
    id: 'basic',
    name: 'Artiste Plan',
    subtitle: 'Basic',
    price: 18000,
    amount: 18000,
    original: 45000,
    period: 'Annually',
    temporary: false,
    accounts: '1 Artist Account',
    icon: Music,
    popular: false,
    features: [
      '1 Artist Account',
      'Unlimited releases',
      'Analytics suite',
      '4–7 day delivery',
      'Single, Album, EP support',
    ],
  },
  {
    id: 'premium',
    name: 'Record Label Plan',
    subtitle: 'Premium',
    price: 35000,
    amount: 35000,
    original: 65000,
    period: 'Annually',
    temporary: false,
    accounts: '10–15 Artist Accounts',
    icon: Users,
    popular: true,
    features: [
      '10–15 Artist Accounts',
      'Unlimited releases',
      'Single, Album, EP upload',
      'Easy payouts',
      '4–7 day delivery',
    ],
  },
  {
    id: 'plus',
    name: 'Record Label Plus',
    subtitle: 'Plus',
    price: 50000,
    amount: 50000,
    original: 110000,
    period: 'Annually',
    temporary: false,
    accounts: '20+ Artist Accounts',
    icon: Users,
    popular: false,
    features: [
      '20+ Artist Accounts',
      'Unlimited releases',
      'Single, EP, Album support',
      'Easy payouts',
      'Priority delivery',
    ],
  },
  {
    id: 'standard',
    name: 'Enterprise Edition',
    subtitle: 'Standard',
    price: 150000,
    amount: 150000,
    original: 450000,
    period: 'Annually',
    temporary: false,
    accounts: 'Unlimited Accounts',
    icon: Globe,
    popular: false,
    features: [
      'Unlimited Artist Accounts',
      'Unlimited releases',
      'Single, EP, Album support',
      'Transparent royalty payouts',
      'Priority support',
    ],
  },
];
